### PR TITLE
The display text can be customized, add Chinese translation

### PR DESCRIPTION
**Pull request by dcsmf**
I couldn't find a method to refresh the text display. So if you change the display text in the settings, you need to close the editor and then open it to take effect

### CODE REVIEW

**Comment by dcsmf** [comment]
It was found that some of the code was not implemented

**Comment by nikolaikopernik** [comment]
?

**Comment by dcsmf** [comment]
> ?

I found that I forgot to implement the feature of custom text display templates. I will create PR after implementing it

**Comment by nikolaikopernik** [comment]
Good, I see what you did in your PR and want to merge it. So go ahead and once you are ready I will merge it.

**Pull request closed without merging**
